#!/usr/bin/env python3

import argparse

from kivy.config import Config
Config.set('input', 'mouse', 'mouse,disable_multitouch')

from kivy.app import App
from kivy.uix.widget import Widget
from kivy.graphics.transformation import Matrix
from kivy.core.window import Window
import kivy.graphics, kivy.properties, kivy.event
import random, time, os.path
import hpgl

random.seed(time.time())

class PlotCanvas(Widget, kivy.event.EventDispatcher):
    plot = kivy.properties.ObjectProperty()
    debug_color = kivy.properties.ObjectProperty((1, 1, 1))
    readonly = kivy.properties.BooleanProperty(False)
    
    zoom_xform = kivy.properties.ObjectProperty(Matrix())
    widget_xform = kivy.properties.ObjectProperty(Matrix())

    vx = kivy.properties.NumericProperty(0)
    vy = kivy.properties.NumericProperty(0)
    
    def __init__(self, **kwargs):
        self.register_event_type('on_update_plot')
        super(PlotCanvas, self).__init__(**kwargs)
        self.bind(size=self.update_ratio)
        self.bind(size=self.update_widget_xform, pos=self.update_widget_xform)
        self.bind(plot=self.on_update_plot)
        self.bind(size=self.draw_plot, pos=self.draw_plot, plot=self.draw_plot, zoom_xform=self.draw_plot)
        Window.bind(on_key_down=self.on_key_down)
        Window.bind(on_key_up=self.on_key_up)
        self.move_mode = False
        self.plot_scale = 1.0
        self.plot_inv_scale = 1.0
        self.zoom = 1
        self.update_widget_xform()
        self.increment_zoom(-1, (0, 0))
        self.drag_start = None
        self.drag_start_view = None
        self.jitter_blocks = False
    
    def on_update_plot(self, *args):
        self.draw_plot()

    def update_ratio(self, *args):
        if not self.plot:
            self.plot_scale = 1.0
            self.plot_inv_scale = 1.0
            return
        
        plot_extents = self.plot.extents()
        plot_h = plot_extents[1][1] - plot_extents[0][1]
        self.plot_scale = (self.height - 20) / plot_h
        self.plot_inv_scale = 1.0 / self.plot_scale
    
    def update_widget_xform(self, *args):
        m = Matrix()
        m.translate(self.pos[0], self.pos[1], 0)
        m.scale(self.plot_scale, self.plot_scale, 1)
        self.widget_xform = m

    def draw_plot(self, *args):
        if not self.plot: return

        self.canvas.clear()
        with self.canvas:
            kivy.graphics.ScissorPush(x = self.pos[0], y = self.pos[1], width=self.width, height=self.height)
            kivy.graphics.PushMatrix()

            mi = kivy.graphics.MatrixInstruction()
            mi.matrix = self.widget_xform.multiply(Matrix().translate(self.vx, self.vy, 0)).multiply(self.zoom_xform)

            for block in self.plot:
                block_pen = block.get_pen()
                block_trace = block.trace(self.jitter_blocks)
                if block_trace:
                    if block_pen == 1:
                        kivy.graphics.Color(1, 1, 1, 0.5)
                    elif block_pen == 2:
                        kivy.graphics.Color(1, 0, 0, 0.5)
                    elif block_pen == 3:
                        kivy.graphics.Color(0, 1, 1, 0.5)
                    else:
                        kivy.graphics.Color(0, 1, 0, 0.5)
                    kivy.graphics.Line(points=hpgl.flatten_coords(block_trace))

            kivy.graphics.PopMatrix()
            kivy.graphics.ScissorPop()
    
    def find_nearest_block(self, scaled_x, scaled_y):
        if not self.plot: return

        best_matches, distance = [], 200
        for b in self.plot:
            d = b.distance_to_trace((scaled_x, scaled_y), self.jitter_blocks)
            if d:
                if d == distance:
                    best_matches.append(b)
                elif d < distance:
                    distance = d
                    best_matches = [b]
        
        return best_matches

    def transform_click(self, x, y, xform=None):
        click_xform = xform or (self.widget_xform.multiply(Matrix().translate(self.vx, self.vy, 0)).multiply(self.zoom_xform).inverse())
        plot_click = click_xform.transform_point(x, y, 0)

        return plot_click[0], plot_click[1]

    def calc_zoom_xform(self, zoom, zoom_origin):
        m = Matrix()
        m = m.multiply(Matrix().scale(zoom, zoom, 1))

        return m

    def increment_zoom(self, dir: int, orig: tuple):
        if self.zoom + dir <= 1:
            self.zoom = 1
            self.zoom_xform = Matrix()
            self.vx = 0
            self.vy = 0
        else:
            self.zoom += dir
            self.zoom_xform = self.calc_zoom_xform(self.zoom, orig)

    def on_key_down(self, *args):
        keycode = args[1]
        if keycode == 304:
            self.jitter_blocks = True
            self.draw_plot()

    def on_key_up(self, *args):
        keycode = args[1]
        if keycode == 304:
            self.jitter_blocks = False
            self.draw_plot()

    def on_touch_move(self, touch):
        if not self.collide_point(touch.x, touch.y): return
        if not self.move_mode:
            self.move_mode = True
            self.drag_start = touch.x, touch.y
            self.drag_start_view = self.vx, self.vy
            return
        self.vx = self.drag_start_view[0] + (touch.x - self.drag_start[0]) * self.plot_inv_scale
        self.vy = self.drag_start_view[1] + (touch.y - self.drag_start[1]) * self.plot_inv_scale
        self.draw_plot()

    def on_touch_down(self, touch):
        pass

    def on_touch_up(self, touch):
        if self.move_mode:
            self.move_mode = False
            self.drag_start = None
            return
        
        if not self.collide_point(touch.x, touch.y): return

        if touch.button in ('scrollup', 'scrolldown'):
            self.increment_zoom(1 if touch.button == 'scrolldown' else -1, (touch.x, touch.y))
            return

        if self.readonly: return
        if not self.plot: return
        
        scaled_x, scaled_y = self.transform_click(touch.x, touch.y)
        nearest_block = self.find_nearest_block(scaled_x, scaled_y)
        
        if not nearest_block: return
        
        if touch.button == 'left':
            for nb in nearest_block:
                cur_pen = nb.get_pen()
                nb.set_pen(1 if cur_pen != 1 else 2)
        elif touch.button == 'middle':
            for nb in nearest_block:
                cur_pen = nb.get_pen()
                nb.set_pen(1)
        elif touch.button == 'right':
            connected = self.plot.connectivity(nearest_block[0])
            for c in connected:
                c.set_pen(2)
        else:
            print(touch.button)
        
        self.dispatch('on_update_plot')
        
        return True

class MainWindow(Widget):
    orig_plot = kivy.properties.ObjectProperty()
    opt_plot = kivy.properties.ObjectProperty()

    def __init__(self, outfile, **kwargs):
        super(MainWindow, self).__init__(**kwargs)
        Window.bind(on_key_up=self.on_key_up)
        self.outfile = outfile
        
    def set_plot(self, p):
        self.orig_plot = p.clone()
        self.opt_plot = p.clone()

    def optimize_plot(self):
        if not self.orig_plot: return
        self.opt_plot = hpgl.organize_cuts(self.orig_plot.clone())
        self.write_out()

    def on_key_up(self, *args):
        print(args)
        if args[1] == 115:
            self.set_plot(self.opt_plot)
    
    def write_out(self):
        if not self.opt_plot: return
        with open(self.outfile, 'w') as f:
            f.write(str(self.opt_plot))

class MarkCutsApp(App):
    def __init__(self, plot: hpgl.HPGLPlot, outfile, **kwargs):
        self.plot = plot
        self.outfile = outfile
        super(MarkCutsApp, self).__init__(**kwargs)

    def build(self):
        self.mainwin = MainWindow(self.outfile)
        self.mainwin.set_plot(self.plot)
        return self.mainwin # PlotCanvas(self.plot)


def do_main():
    arg_parser = argparse.ArgumentParser(description="Mark HPGL blocks for cutting vs. plotting.")
    arg_parser.add_argument('--out', type=str, help="Output file, otherwise automatically generate name.")
    arg_parser.add_argument('file', type=str, help="The file of HPGL commands to send.")
    args = arg_parser.parse_args()
    plot = hpgl.parse_file(args.file)

    outfile = os.path.splitext(args.file)[0] + "-preprocessed.plt"

    MarkCutsApp(plot, outfile).run()


if __name__ == '__main__':
    do_main()