#!/usr/bin/env python3

import argparse

import hpgl

arg_parser = argparse.ArgumentParser(description="flip a plt")
arg_parser.add_argument('file', type=str)
args = arg_parser.parse_args()

plot = hpgl.parse_file(args.file)

print(repr(plot))
