#!/usr/bin/env python3

arg_parser = argparse.ArgumentParser(description="Filter a PLT file for fabric cutting.")
arg_parser.add_argument('--mirror', default=False, const=True, action='store_const', help="flip in the y axis via IP/SC manipulation.")
arg_parser.add_argument('--traces', default=False, const=True, action='store_const', help="filter out non-traceable blocks (labels, etc.).")
arg_parser.add_argument('file', type=str)
args = arg_parser.parse_args()

plot = hpgl.parse_file(args.file)